version: '3.8'  # Optional but good to have

services:
  frontend:
    build: ./frontend
    ports:
      - "8087:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
